services_file: ~/.config/mailctl/services.yaml
oauth2_dir: ~/.local/var/mailctl

encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - 9382FD1D3B50C6FAC6DA48E5C3C24114E3E65AA6
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt
