[manager]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
linemode = "size"
show_symlink = true

[perview]
image_filter = "lanczos3"

[input]
origin = "bottom-center"


[open]
rules = [
  { mime = "text/*",          use = [ "edit", "reveal" ] },
  { mime = "image/*",         use = [ "open", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { mime = "inode/x-empty",   use = [ "edit", "reveal" ] },

  { mime = "application/*zip", use = [ "extract", "reveal" ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },

  { mime = "application/json", use = [ "edit", "reveal" ] },
  { mime = "*/javascript",     use = [ "edit", "reveal" ] },

  { mime = "*", use = ["open", "reveal", "edit"] },
]

[opener]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "audio/*",   run = "exifaudio"},
]

prepend_preloaders = [
]
