## oama version 0.12

## This is a YAML configuration file, indentation matters.
## Double ## indicates comments while single # default values.
## Not all defaults are shown, for full list run `oama printenv`
## and look at the `services:` section.

## Possible options for keeping refresh and access tokens:
## GPG - in a gpg encrypted file ~/.local/var/oama/<email-address>.oauth
## GRING - in the default Gnome keyring
##
## Choose exactly one.

# encryption:
#     tag: GRING

encryption:
  tag: GPG
  contents: 9382FD1D3B50C6FAC6DA48E5C3C24114E3E65AA6

# It must be >= 1024
redirect_port: 8081

## Builtin service providers
## - google
## - microsoft
## Required fields: client_id, client_secret
##
services:
  google:
    client_id: 406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com
    client_secret: kSmqreRr0qwBWJgbf5Y-PjSU
    auth_scope: https://mail.google.com/

  # microsoft:
  #   client_id: application-CLIENT-ID
  #   client_secret: application-CLIENT_SECRET
  #   auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All
  #     https://outlook.office365.com/SMTP.Send
  #     offline_access
  #   tenant: common

  ## User configured providers
  ## Required fields: client_id, client_secret, auth_endpoint, auth_scope, token_endpoint
  ##
  ## For example:
  # yahoo:
  #   client_id: application-CLIENT-ID
  #   client_secret: application-CLIENT_SECRET
  #   auth_endpoint: EDIT-ME!
  #   auth_scope: EDIT-ME!
  #   token_endpoint: EDIT-ME!
