#!/bin/bash
music_dir="$HOME/usr/Documents/Music"
previewdir="${XDG_CACHE_HOME:-$HOME/.cache/}/ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
previewname="$previewdir/$(mpc --format %album% current | base64).png"

[ -d $previewdir ] || mkdir -p $previewdir
# echo $previewname
[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf scale=128:128 "$previewname" > /dev/null 2>&1

notify-send -r 27072 "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" -i "$previewname"
